import type { AnalysisResult } from "@dw/llm";
import { config } from "@dw/config";
import { isDevopsConfigured } from "@dw/validators/devops-env";

const GITHUB_API = "https://api.github.com";

function getHeaders(): Record<string, string> {
  const token = config.devops.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN is not set");
  return {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
    Accept: "application/vnd.github.v3+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

function getRepo(): string {
  const repo = config.devops.GITHUB_REPO;
  if (!repo) throw new Error("GITHUB_REPO is not set");
  return repo;
}

// ─────────────────────────────────────────────
// PR Comment
// ─────────────────────────────────────────────

export async function postPrComment(
  prNumber: number,
  analysis: AnalysisResult,
  eventType: "ci_failure" | "sentry_error",
): Promise<void> {
  if (!isDevopsConfigured()) {
    console.info("[DevOps not configured] Skipping PR comment");
    return;
  }
  const body = formatComment(analysis, eventType);
  const res = await fetch(
    `${GITHUB_API}/repos/${getRepo()}/issues/${prNumber}/comments`,
    { method: "POST", headers: getHeaders(), body: JSON.stringify({ body }) },
  );
  if (!res.ok) throw new Error(`GitHub PR comment failed: ${res.status}`);
}

// ─────────────────────────────────────────────
// Issue
// ─────────────────────────────────────────────

export async function createIssue(
  title: string,
  analysis: AnalysisResult,
  extraLabels: string[] = [],
): Promise<{ number: number; url: string }> {
  if (!isDevopsConfigured()) {
    console.info("[DevOps not configured] Skipping GitHub issue creation");
    return { number: 0, url: "" };
  }
  const labels = [
    "platform-agent",
    `severity:${analysis.severity}`,
    ...analysis.labels,
    ...extraLabels,
  ];
  const res = await fetch(`${GITHUB_API}/repos/${getRepo()}/issues`, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify({ title, body: formatIssueBody(analysis), labels }),
  });
  if (!res.ok) throw new Error(`GitHub issue creation failed: ${res.status}`);
  const data = (await res.json()) as { number: number; html_url: string };
  return { number: data.number, url: data.html_url };
}

// ─────────────────────────────────────────────
// Commit file to repo
// ─────────────────────────────────────────────

export async function commitFile(
  filePath: string,
  content: string,
  commitMessage: string,
): Promise<void> {
  if (!isDevopsConfigured()) {
    console.info("[DevOps not configured] Skipping incident doc commit");
    return;
  }
  const encodedContent = Buffer.from(content, "utf-8").toString("base64");

  let existingSha: string | undefined;
  try {
    const checkRes = await fetch(
      `${GITHUB_API}/repos/${getRepo()}/contents/${filePath}`,
      { headers: getHeaders() },
    );
    if (checkRes.ok) {
      const existing = (await checkRes.json()) as { sha: string };
      existingSha = existing.sha;
    }
  } catch {
    // File doesn't exist yet — that's fine, we'll create it
  }

  const res = await fetch(
    `${GITHUB_API}/repos/${getRepo()}/contents/${filePath}`,
    {
      method: "PUT",
      headers: getHeaders(),
      body: JSON.stringify({
        message: commitMessage,
        content: encodedContent,
        ...(existingSha !== undefined ? { sha: existingSha } : {}),
      }),
    },
  );
  if (!res.ok) throw new Error(`GitHub file commit failed: ${res.status}`);
}

// ─────────────────────────────────────────────
// Formatters
// ─────────────────────────────────────────────

const SEVERITY_EMOJI: Record<AnalysisResult["severity"], string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🟢",
};

function formatComment(analysis: AnalysisResult, eventType: string): string {
  const emoji = SEVERITY_EMOJI[analysis.severity];
  const title =
    eventType === "ci_failure" ? "CI Failure Analysis" : "Incident Analysis";
  return `## ${emoji} ${title} — \`${analysis.severity.toUpperCase()}\`

> ${analysis.summary}

### Root Cause
${analysis.rootCause}

### Impact
${analysis.impact}

### Suggested Fix
${analysis.suggestedFix}

---
<sub>🤖 Generated by platform-agent · Labels: ${analysis.labels.join(", ")}</sub>`;
}

function formatIssueBody(analysis: AnalysisResult): string {
  const emoji = SEVERITY_EMOJI[analysis.severity];
  return `${emoji} **Severity**: \`${analysis.severity.toUpperCase()}\`

## Summary
${analysis.summary}

## Root Cause
${analysis.rootCause}

## Impact
${analysis.impact}

## Suggested Fix
${analysis.suggestedFix}

---
<sub>🤖 Generated by platform-agent</sub>`;
}
