import type { IncidentDocResult, PlatformEvent } from "@dw/contracts";
import type { AnalysisResult } from "@dw/llm";

import { commitFile } from "./github";

export async function generateAndCommitIncidentDoc(
  event: PlatformEvent,
  analysis: AnalysisResult,
  issueUrl?: string,
): Promise<IncidentDocResult> {
  const isoDate = new Date().toISOString();
  const date = isoDate.split("T")[0] ?? isoDate.slice(0, 10);
  const slug = buildSlug(analysis.summary);
  const filePath = `docs/incidents/${date}-${slug}.md`;

  // [platform-agent] tag is required — the GitHub webhook handler uses it
  // to filter out agent-originated CI runs and prevent the feedback loop:
  //   CI failure → incident doc commit → CI run → incident doc commit → ...
  await commitFile(
    filePath,
    buildIncidentDoc(event, analysis, date, issueUrl),
    `docs(incident): ${date} — ${analysis.summary.slice(0, 72)} [platform-agent]`,
  );

  return { filePath, slug };
}

function buildIncidentDoc(
  event: PlatformEvent,
  analysis: AnalysisResult,
  date: string,
  issueUrl?: string,
): string {
  const severityBadge: Record<AnalysisResult["severity"], string> = {
    critical: "🔴 CRITICAL",
    high: "🟠 HIGH",
    medium: "🟡 MEDIUM",
    low: "🟢 LOW",
  };

  const typeLabel =
    event.type === "ci_failure"
      ? "CI Failure"
      : event.type === "security_alert"
        ? "Security Alert"
        : "Runtime Error";

  return `# Incident: ${analysis.summary}

| Field | Value |
|---|---|
| **Date** | ${date} |
| **Type** | ${typeLabel} |
| **Severity** | ${severityBadge[analysis.severity]} |
| **Service** | \`${event.service}\` |
${issueUrl !== undefined ? `| **GitHub Issue** | ${issueUrl} |` : ""}

## Summary
${analysis.summary}

## Root Cause
${analysis.rootCause}

## Impact
${analysis.impact}

## Resolution
${analysis.suggestedFix}

## Context
${buildContextSection(event)}

---
*Generated by platform-agent on ${new Date().toISOString()}*
*Labels: ${analysis.labels.join(", ")}*
`;
}

function buildContextSection(event: PlatformEvent): string {
  if (event.type === "ci_failure") {
    const c = event.context;
    return `- **Workflow**: \`${c.workflow}\`
- **Branch**: \`${c.branch}\`
- **Commit**: \`${c.commitSha}\`
${c.prNumber !== null ? `- **PR**: #${c.prNumber} — ${c.prTitle ?? ""}` : "- **No PR** (branch push)"}
- **Failed step**: ${c.failedStep}
- **Triggered by**: ${c.triggeredBy}`;
  }

  if (event.type === "security_alert") {
    const c = event.context;
    return `- **Package**: \`${c.packageName}\` (${c.ecosystem})
- **Vulnerable range**: \`${c.vulnerableVersionRange}\`
- **Fixed version**: ${c.firstPatchedVersion ?? "no fix available"}
- **Scope**: ${c.scope ?? "unknown"}
- **Manifest**: \`${c.manifestPath}\`
${c.cveId !== null ? `- **CVE**: ${c.cveId}` : ""}
- **GHSA**: ${c.ghsaId}
- **Alert**: ${c.alertUrl}`;
  }

  // sentry_error
  const c = event.context;
  return `- **Error**: \`${c.title}\`
- **Culprit**: \`${c.culprit}\`
- **Environment**: \`${c.environment}\`
${c.route !== null ? `- **Route**: \`${c.route}\`` : ""}
- **Users affected**: ${c.userCount}
- **First seen**: ${c.firstSeen}
- **Sentry**: ${c.issueUrl}`;
}

function buildSlug(summary: string): string {
  return summary
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 50);
}
