import type { IncidentDocResult, PlatformEvent } from "@dw/contracts";
import type { AnalysisResult } from "@dw/llm";

import { commitFile } from "./github";

export async function generateAndCommitIncidentDoc(
  event: PlatformEvent,
  analysis: AnalysisResult,
  issueUrl?: string,
): Promise<IncidentDocResult> {
  // Avoid non-null assertion (!) — split("T")[0] can be undefined
  // if the string is empty, so we provide a fallback.
  const isoDate = new Date().toISOString();
  const date = isoDate.split("T")[0] ?? isoDate.slice(0, 10);
  const slug = buildSlug(analysis.summary);
  const filePath = `docs/incidents/${date}-${slug}.md`;

  await commitFile(
    filePath,
    buildIncidentDoc(event, analysis, date, issueUrl),
    `docs(incident): ${date} — ${analysis.summary.slice(0, 72)}`,
  );

  return { filePath, slug };
}

function buildIncidentDoc(
  event: PlatformEvent,
  analysis: AnalysisResult,
  date: string,
  issueUrl?: string,
): string {
  const severityBadge: Record<AnalysisResult["severity"], string> = {
    critical: "🔴 CRITICAL",
    high: "🟠 HIGH",
    medium: "🟡 MEDIUM",
    low: "🟢 LOW",
  };
  const label = event.type === "ci_failure" ? "CI Failure" : "Runtime Error";

  return `# Incident: ${analysis.summary}

| Field | Value |
|---|---|
| **Date** | ${date} |
| **Type** | ${label} |
| **Severity** | ${severityBadge[analysis.severity]} |
| **Service** | \`${event.service}\` |
${issueUrl !== undefined ? `| **GitHub Issue** | ${issueUrl} |` : ""}

## Summary
${analysis.summary}

## Root Cause
${analysis.rootCause}

## Impact
${analysis.impact}

## Resolution
${analysis.suggestedFix}

## Context
${buildContextSection(event)}

---
*Generated by platform-agent on ${new Date().toISOString()}*
*Labels: ${analysis.labels.join(", ")}*
`;
}

function buildContextSection(event: PlatformEvent): string {
  if (event.type === "ci_failure") {
    const c = event.context;
    return `- **Workflow**: \`${c.workflow}\`
- **Branch**: \`${c.branch}\`
- **Commit**: \`${c.commitSha}\`
${c.prNumber !== null ? `- **PR**: #${c.prNumber} — ${c.prTitle ?? ""}` : "- **No PR** (branch push)"}
- **Failed step**: ${c.failedStep}
- **Triggered by**: ${c.triggeredBy}`;
  }
  const c = event.context;
  return `- **Error**: \`${c.title}\`
- **Culprit**: \`${c.culprit}\`
- **Environment**: \`${c.environment}\`
${c.route !== null ? `- **Route**: \`${c.route}\`` : ""}
- **Users affected**: ${c.userCount}
- **First seen**: ${c.firstSeen}
- **Sentry**: ${c.issueUrl}`;
}

function buildSlug(summary: string): string {
  return summary
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 50);
}
