// ─────────────────────────────────────────────
// Incident status lifecycle
//
// open         → detected, not yet analyzed or actioned
// investigating → agent is actively analyzing
// monitoring   → Sentry resolved but watching for recurrence
// resolved     → confirmed fixed (GitHub issue closed or manual)
// closed       → historical, no further action needed
// ─────────────────────────────────────────────

/**
 * Literal marker embedded in every demo Sentry capture's exception message
 * (see apps/nextjs/src/lib/sentry-capture.ts). Sentry's outbound webhook
 * does not preserve custom tags set at capture time — only the message
 * text survives the round trip — so this string is the only reliable,
 * code-checkable signal available to runSentryAgent(). Checked verbatim
 * against event.context.title; never left to LLM inference.
 */
export const DEMO_SENTRY_MESSAGE_PREFIX =
  "[Demo] Platform agent integration test";

export type IncidentStatus =
  | "open"
  | "investigating"
  | "monitoring"
  | "resolved"
  | "closed";

export const INCIDENT_STATUSES: IncidentStatus[] = [
  "open",
  "investigating",
  "monitoring",
  "resolved",
  "closed",
];

export interface IncidentDocResult {
  filePath: string;
  slug: string;
}

export interface IncidentRecord {
  // ── Identity ──────────────────────────────────────────────────────────────
  type:
    | "ci_failure"
    | "sentry_error"
    | "security_alert"
    | "clerk_event"
    | "uptime_failure"
    | "supabase_advisory";
  id: string;
  service: string;
  timestamp: string;

  // ── AI analysis ───────────────────────────────────────────────────────────
  summary: string;
  rootCause: string;
  severity: "critical" | "high" | "medium" | "low";
  labels: string[];

  // ── Status lifecycle ──────────────────────────────────────────────────────
  status: IncidentStatus;
  updatedAt: string;

  // ── Resolution ────────────────────────────────────────────────────────────
  resolvedAt?: string;
  resolvedBy?: "github_issue_closed" | "sentry_resolved" | "manual";
  resolutionNote?: string;

  // ── Correlation ───────────────────────────────────────────────────────────
  /** GitHub issue URL created by the agent */
  issueUrl?: string;
  /** GitHub issue number for webhook resolution matching */
  githubIssueNumber?: number;
  /**
   * Set when the agent attempted to create a GitHub issue and the call
   * failed (rate limit, transient 5xx, auth hiccup) — distinguishes a
   * genuine failure from incident types that never attempt issue creation
   * (e.g. supabase_advisory). Cleared implicitly once a manual resolve or
   * a later successful backfill sets issueUrl/githubIssueNumber.
   * See platform/ai/src/analyzers/{ci,sentry,security}-agent.ts.
   */
  githubIssueError?: string;
  /**
   * Sentry issue ID for sentry_error incidents.
   * Dependabot alert number (as string) for security_alert incidents.
   */
  sentryIssueId?: string;
  /** Sentry issue URL for direct navigation to the Sentry dashboard */
  sentryIssueUrl?: string;
  /** Incident doc path committed to the repo */
  incidentDocPath?: string;
  /** Deployment SHA at time of incident — for correlation */
  commitSha?: string;
  /** Branch where the incident occurred */
  branch?: string;
  /**
   * True when this incident was generated by the recruiter-facing demo
   * panel (POST /api/demo/trigger/*) rather than a real production event.
   * Set explicitly by the triggering payload (CiJobPayload.isDemo) —
   * never inferred from message text or ID shape. Used to keep demo
   * events out of recurrence-detection context for real incidents.
   */
  isDemo?: boolean;
}

export interface IncidentSummary {
  id: string;
  type: IncidentRecord["type"];
  service: string;
  severity: IncidentRecord["severity"];
  status: IncidentStatus;
  summary: string;
  timestamp: string;
  updatedAt: string;
  issueUrl?: string;
  githubIssueError?: string;
  sentryIssueId?: string;
  sentryIssueUrl?: string;
  githubIssueNumber?: number;
}

export function toIncidentSummary(record: IncidentRecord): IncidentSummary {
  return {
    id: record.id,
    type: record.type,
    service: record.service,
    severity: record.severity,
    status: record.status,
    summary: record.summary,
    timestamp: record.timestamp,
    updatedAt: record.updatedAt,
    issueUrl: record.issueUrl,
    githubIssueError: record.githubIssueError,
    sentryIssueId: record.sentryIssueId,
    sentryIssueUrl: record.sentryIssueUrl,
    githubIssueNumber: record.githubIssueNumber,
  };
}
